export const RECEIVE_HAEDCATES = 'receive_haedcates'
export const RECEIVE_FOCUSLISTS = 'receive_focusLists'
export const RECEIVE_TAGLISTS = 'receive_tagLists'
export const RECEIVE_NEWITEMLISTS = 'receive_newItemLists'
export const RECEIVE_POPULARITEMLISTS = 'receive_popularItemLists'
export const RECEIVE_FLASHSALEINDEXVO = 'receive_flashSaleIndexVO'
export const RECEIVE_TOPICLISTS = 'receive_topicLists'
export const RECEIVE_CATELISTS = 'receive_cateLists'

export const RECEIVE_BANNERS = 'receive_banners'
